### PR TITLE
Support for the new input system

### PR DESCRIPTION
**Pull request by Gusinuhe**
### Description

This PR adds support to the new Input System.

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?

Try along with https://github.com/Innoactive/XR-Interaction-Component/pull/78

### CODE REVIEW

**Review by SimonTheSourcerer — CHANGES_REQUESTED** [review]
Only new Input System does not work for me, UI does not react to anything.

**Comment by Gusinuhe** [comment]
> Only new Input System does not work for me, UI does not react to anything.

I just tested it on a brand new project, everything seems to work fine.

Make sure to use the `[XR_Setup_Action_Based]` when testing UI in the new input system and to use `[XR_Setup_Device_Based]` when testing the legacy input system.

**Review by SimonTheSourcerer — APPROVED** [review]
Does work for me in a new project, does not updating an old project. Dunno if i should approve or not to be honest.

**Comment by Gusinuhe** [comment]
> Does work for me in a new project, does not updating an old project. Dunno if i should approve or not to be honest.

It should be fine now, I recommend a sanity check test

**Pull request merged**
